---
- name: add GitLab package repository
  shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
  args:
    creates: /etc/apt/sources.list.d/runner_gitlab-runner.list

- name: add Docker package repository
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    touch /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: install packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - docker-ce
    - gitlab-runner
    - unattended-upgrades

- name: configure automatic updates
  copy:
    src: etc/apt/periodic.conf
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644

- name: install Docker Machine
  get_url:
    url: https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Linux-x86_64
    dest: /usr/local/bin/docker-machine
    owner: root
    group: root
    mode: 0755
