---
- name: provision Google Cloud instances
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - provision
  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags:
    - provision

- name: deploy GitLab Runner
  hosts: tag_gitlab-master
  remote_user: "{{user}}"
  become: True
  roles:
    - gitlab
  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags:
    - deploy
