---
- name: provision instances
  gce:
    instance_names: "{{instance_name}}"
    tags:
      - "{{instance_tag}}"
    zone: "{{zone}}"
    machine_type: "{{machine_type}}"
    image: "{{image}}"
    network: "{{network_name}}"
    disk_size: "{{disk_size}}"
    metadata: '{"ssh-keys": "{{user}}:{{ssh_key}}"}'
    state: present
