---
- name: provision instances
  gce:
    instance_names: "{{instance_name_master}}"
    tags:
      - "{{group_tag}}"
      - "{{instance_tag_master}}"
    zone: "{{zone}}"
    machine_type: "{{machine_type_master}}"
    image: "{{image_master}}"
    network: "{{network_name}}"
    disk_size: "{{disk_size_master}}"
    metadata: '{"ssh-keys": "{{user}}:{{ssh_key}}"}'
    state: present
  register: gce

- name: wait for SSH on instances
  wait_for:
    host: "{{item.public_ip}}"
    port: 22
    delay: 5
    timeout: 300
    state: started
  with_items: "{{gce.instance_data}}"
