---
- name: configure network
  gcp_compute_network:
    name: "{{network_name}}"
    auto_create_subnetworks: 'true'
    state: present

- name: configure firewall rules
  gcp_compute_firewall:
    name: "{{network_name}}-firewall"
    network:
      self_link: "{{network_name}}"
    allowed:
      - ip_protocol: icmp
      - ip_protocol: tcp
        ports:
          - "22"
    source_ranges:
      - "0.0.0.0/0"
    state: present

- name: configure firewall rules for Docker Registry
  gcp_compute_firewall:
    name: "{{network_name}}-firewall-docker"
    network:
      self_link: "{{network_name}}"
    allowed:
      - ip_protocol: tcp
        ports:
          - "6000"
    source_ranges:
      - "10.128.0.0/9"
    state: present
