---
# Google Compute Engine configuration
zone: us-west1-b
network_name: gitlab
group_tag: gitlab
instance_name_master: gitlab-master
instance_name_worker: gitlab-woker
instance_tag_master: gitlab-master
instance_tag_worker: gitlab-worker
machine_type_master: n1-standard-1
machine_type_worker: n1-standard-8
image_master: ubuntu-1604
image_worker: https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/family/coreos-stable
disk_size_master: 64 # GB
disk_size_worker: 16 # GB

# GitLab Runner configuration
runner_name: gce-autoscale-test4
runner_limit: 12 # maximum number of concurrent jobs to process
runner_idle_nodes: 0 # number of nodes to keep idle
runner_idle_time: 600 # (seconds) time machine is idle before being removed
runner_max_builds: 20 # number of times machine is reused before being replaced
